# Generated by Django 4.2.27 on 2025-12-29 08:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('authority', models.CharField(choices=[('PTA', 'Provincial Transport Authority'), ('RTA', 'Regional Transport Authority')], max_length=10)),
                ('permit_type', models.CharField(choices=[('transport', 'Transport'), ('goods', 'Goods'), ('passenger', 'Passenger'), ('commercial', 'Commercial')], max_length=20)),
                ('vehicle_number', models.CharField(db_index=True, max_length=20)),
                ('vehicle_make', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_year', models.IntegerField(blank=True, null=True)),
                ('vehicle_capacity', models.IntegerField(blank=True, null=True)),
                ('owner_name', models.CharField(max_length=200)),
                ('owner_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('owner_phone', models.CharField(max_length=20)),
                ('owner_address', models.TextField(blank=True, null=True)),
                ('owner_cnic', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('pending', 'Pending')], db_index=True, default='pending', max_length=20)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to='permits/%Y/%m/')),
                ('approved_routes', models.TextField(blank=True, help_text='Comma separated routes', null=True)),
                ('restrictions', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='PermitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('activated', 'Activated'), ('deactivated', 'Deactivated'), ('cancelled', 'Cancelled'), ('renewed', 'Renewed')], max_length=20)),
                ('performed_by', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='permits.permit')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='permit',
            index=models.Index(fields=['vehicle_number', 'status'], name='permits_per_vehicle_cbcb31_idx'),
        ),
        migrations.AddIndex(
            model_name='permit',
            index=models.Index(fields=['owner_email'], name='permits_per_owner_e_1bdf61_idx'),
        ),
        migrations.AddIndex(
            model_name='permit',
            index=models.Index(fields=['valid_from', 'valid_to'], name='permits_per_valid_f_659b30_idx'),
        ),
    ]
