# Generated by Django 4.2.27 on 2026-01-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0003_user_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='Role identifier (lowercase, no spaces)', max_length=50, unique=True),
        ),
    ]
