# Generated by Django 4.2.27 on 2026-01-25 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0004_alter_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('registration', 'Vehicle Registration'), ('insurance', 'Insurance Document'), ('tax', 'Tax Document'), ('fitness', 'Fitness Certificate'), ('cnic', 'CNIC Copy'), ('route_map', 'Route Map'), ('authorization', 'Authorization Letter'), ('other', 'Other Document')], max_length=20)),
                ('file', models.FileField(upload_to='permit_documents/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_by', models.CharField(blank=True, max_length=200, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_documents', to='permits.permit')),
            ],
            options={
                'verbose_name': 'Permit Document',
                'verbose_name_plural': 'Permit Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
