# Generated by Django 4.2.27 on 2026-01-25 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permits', '0005_permitdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permit',
            name='assigned_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='permit',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Supervisor/Operator/Administrator who is responsible for this permit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_permits', to=settings.AUTH_USER_MODEL),
        ),
    ]
