# Generated by Django 4.2.27 on 2026-01-25 13:36

from django.db import migrations


def migrate_permit_types(apps, schema_editor):
    """Ensure all permits have a permit_type FK set"""
    Permit = apps.get_model('permits', 'Permit')
    PermitType = apps.get_model('permits', 'PermitType')
    
    # By this point, migration 0008 has already converted the FK
    # Just ensure any NULL values are set to a default
    try:
        # Get the first permit type or create one
        permit_type = PermitType.objects.first()
        if permit_type:
            updated_count = Permit.objects.filter(permit_type__isnull=True).update(permit_type=permit_type)
            print(f"Set {updated_count} permits to default PermitType: {permit_type.name}")
        else:
            print("No PermitTypes found in database")
    except Exception as e:
        print(f"Error in migration: {e}")


def reverse_migrate(apps, schema_editor):
    """Reverse migration - note: data loss as we can't convert back to strings"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0008_permit_type_fk_migration'),
    ]

    operations = [
        migrations.RunPython(migrate_permit_types, reverse_migrate),
    ]
