# Generated by Django 4.2.27 on 2026-01-25 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0009_migrate_permit_type_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='permit_type',
            field=models.ForeignKey(blank=True, help_text='Permit type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permits', to='permits.permittype'),
        ),
    ]
