# Generated by Django 4.2.27 on 2026-02-13 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0010_permit_vehicle_type_alter_permit_permit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, help_text='Vehicle type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permits', to='permits.vehicletype'),
        ),
    ]
