# Generated by Django 4.2.27 on 2026-02-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0012_vehicletype_permit_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
