# Generated by Django 4.2.27 on 2026-02-26 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permits', '0013_alter_permit_owner_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_type', models.CharField(choices=[('sbp', 'State Bank of Pakistan'), ('nbp', 'National Bank of Pakistan'), ('hbl', 'Habib Bank Limited'), ('ufb', 'United Bank Limited'), ('abl', 'Allied Bank'), ('scb', 'Standard Chartered Bank'), ('other', 'Other')], default='other', max_length=20)),
                ('account_title', models.CharField(help_text='Name of account holder/organization', max_length=200)),
                ('account_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('iban', models.CharField(help_text='International Bank Account Number', max_length=50, unique=True)),
                ('branch_code', models.CharField(blank=True, max_length=20, null=True)),
                ('routing_number', models.CharField(blank=True, max_length=20, null=True)),
                ('swift_code', models.CharField(blank=True, help_text='SWIFT code for international transfers', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary account for automatic payment collection')),
                ('description', models.TextField(blank=True, help_text='Additional notes about this account', null=True)),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['-is_primary', '-is_active', 'bank_name'],
            },
        ),
        migrations.CreateModel(
            name='Chalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chalan_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('owner_name', models.CharField(max_length=200)),
                ('owner_cnic', models.CharField(db_index=True, help_text="Owner's CNIC for identification", max_length=20)),
                ('owner_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('car_number', models.CharField(db_index=True, help_text='Vehicle registration number', max_length=20)),
                ('violation_description', models.TextField(help_text='Description of the traffic violation')),
                ('fees_amount', models.DecimalField(decimal_places=2, help_text='Amount of fine/fee for this violation', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed'), ('resolved', 'Resolved')], db_index=True, default='pending', max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid by the owner', max_digits=10)),
                ('payment_date', models.DateTimeField(blank=True, help_text='When the chalan was paid', null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment transaction reference', max_length=100, null=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('issue_location', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='chalan_documents/%Y/%m/')),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chalan',
                'verbose_name_plural': 'Chalans',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='ChalanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('paid', 'Payment Received'), ('cancelled', 'Cancelled'), ('fee_updated', 'Fee Updated'), ('disputed', 'Disputed'), ('resolved', 'Resolved')], max_length=20)),
                ('performed_by', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Stores field changes')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Chalan History',
                'verbose_name_plural': 'Chalan Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text="Unique code like 'permit_create', 'permit_approve', etc.", max_length=50, unique=True)),
                ('name', models.CharField(help_text='Human-readable event name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this event logs')),
                ('category', models.CharField(choices=[('permit', 'Permit Operations'), ('document', 'Document Management'), ('user', 'User Management'), ('role', 'Role Management'), ('system', 'System Operations'), ('report', 'Reporting'), ('audit', 'Audit Operations')], default='permit', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this event can be logged')),
                ('is_auditable', models.BooleanField(default=True, help_text='Whether logs of this event appear in audit reports')),
                ('requires_approval', models.BooleanField(default=False, help_text='Whether this action requires approval before execution')),
                ('severity_level', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=1, help_text='Severity for audit purposes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.AddField(
            model_name='permit',
            name='previous_permits_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of IDs of previous permits that this permit is a renewal of (tracks permit chain for expired permits)'),
        ),
        migrations.AddField(
            model_name='permit',
            name='user_owner',
            field=models.ForeignKey(blank=True, help_text='User who owns this permit (created it)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_permits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(choices=[('permit_view', 'View Permits'), ('permit_create', 'Create Permits'), ('permit_edit', 'Edit Permits'), ('permit_delete', 'Delete Permits'), ('permit_check', 'Check Permits'), ('permit_submit', 'Submit Permits'), ('permit_share', 'Share Permits'), ('permit_renew', 'Renew Permits'), ('permit_cancel', 'Cancel Permits'), ('chalan_view', 'View Chalans'), ('chalan_create', 'Create Chalans'), ('chalan_edit', 'Edit Chalans'), ('chalan_manage_fees', 'Manage Chalan Fees'), ('chalan_mark_paid', 'Mark Chalan as Paid'), ('chalan_cancel', 'Cancel Chalans'), ('chalan_vehicle_fee_view', 'View Vehicle Fee Structures'), ('chalan_vehicle_fee_manage', 'Manage Vehicle Fee Structures'), ('user_manage', 'Manage Users'), ('role_manage', 'Manage Roles'), ('report_view', 'View Reports'), ('dashboard_view', 'View Dashboard'), ('employee', 'Is Employee')], help_text='System feature identifier', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='permit_number',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated on submission', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('pending', 'Pending')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='permit',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='vehicle_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='VehicleFeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fee', models.DecimalField(decimal_places=2, help_text='Base fee for this vehicle type', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Description or notes about this fee structure', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this fee structure is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this fee structure', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_fee_updates', to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.OneToOneField(help_text='Vehicle type', on_delete=django.db.models.deletion.CASCADE, related_name='fee_structure', to='permits.vehicletype')),
            ],
            options={
                'verbose_name': 'Vehicle Fee Structure',
                'verbose_name_plural': 'Vehicle Fee Structures',
                'ordering': ['vehicle_type__name'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_retention_days', models.IntegerField(default=365, help_text='Number of days to retain event logs')),
                ('enable_detailed_logging', models.BooleanField(default=True, help_text='Whether to log detailed change information')),
                ('audit_critical_events', models.BooleanField(default=True, help_text='Automatically flag critical events for audit review')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('admin_user', models.ForeignKey(blank=True, help_text='Super admin user that cannot be deleted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('permit_assigned', 'Permit Assigned'), ('permit_status_changed', 'Permit Status Changed'), ('permit_updated', 'Permit Updated'), ('system_info', 'System Information'), ('alert', 'Alert'), ('reminder', 'Reminder')], db_index=True, default='system_info', max_length=50)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Whether user has read this notification')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the user read this notification', null=True)),
                ('email_sent', models.BooleanField(default=False, help_text='Whether email notification was sent')),
                ('email_sent_at', models.DateTimeField(blank=True, help_text='When the email notification was sent', null=True)),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate to when notification is clicked', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permit', models.ForeignKey(blank=True, help_text='Related permit (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='permits.permit')),
                ('user', models.ForeignKey(help_text='User receiving the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(help_text="Type of object affected (e.g., 'permit', 'user', 'document')", max_length=50)),
                ('object_id', models.IntegerField(blank=True, help_text='ID of the affected object', null=True)),
                ('object_description', models.CharField(blank=True, help_text='Human-readable description of affected object', max_length=500)),
                ('changes', models.JSONField(blank=True, default=dict, help_text="Dictionary of changes: {'field_name': {'old': old_value, 'new': new_value}}")),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string of the request')),
                ('request_method', models.CharField(blank=True, help_text='HTTP method (GET, POST, PUT, DELETE, etc.)', max_length=10)),
                ('endpoint', models.CharField(blank=True, help_text='API endpoint that was called', max_length=500)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='success', help_text='Outcome of the action', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed')),
                ('notes', models.TextField(blank=True, help_text='Additional context or notes about this action')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred')),
                ('event', models.ForeignKey(help_text='The event type', on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='permits.event')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Log',
                'verbose_name_plural': 'Event Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['code', 'is_active'], name='permits_eve_code_c8cc7b_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category'], name='permits_eve_categor_a8900c_idx'),
        ),
        migrations.AddField(
            model_name='chalanhistory',
            name='chalan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='permits.chalan'),
        ),
        migrations.AddField(
            model_name='chalan',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='Bank account for payment collection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chalans', to='permits.bankaccount'),
        ),
        migrations.AddField(
            model_name='chalan',
            name='issued_by',
            field=models.ForeignKey(blank=True, help_text='Officer who issued the chalan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_chalans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chalan',
            name='permit',
            field=models.ForeignKey(help_text='Associated permit', on_delete=django.db.models.deletion.CASCADE, related_name='chalans', to='permits.permit'),
        ),
        migrations.AddField(
            model_name='chalan',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User/Owner against whom chalan is issued', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chalans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chalan',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, help_text='Vehicle type (from permit)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chalans_by_type', to='permits.vehicletype'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='permits_not_user_id_e0ac63_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='permits_not_user_id_cbf45a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', '-created_at'], name='permits_not_notific_74d6d2_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['event', '-timestamp'], name='permits_eve_event_i_af807b_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['user', '-timestamp'], name='permits_eve_user_id_5e283d_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['status', '-timestamp'], name='permits_eve_status_8aeb40_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['content_type', 'object_id'], name='permits_eve_content_ff783b_idx'),
        ),
        migrations.AddIndex(
            model_name='chalan',
            index=models.Index(fields=['car_number', 'status'], name='permits_cha_car_num_e79629_idx'),
        ),
        migrations.AddIndex(
            model_name='chalan',
            index=models.Index(fields=['owner_cnic'], name='permits_cha_owner_c_d76ca4_idx'),
        ),
        migrations.AddIndex(
            model_name='chalan',
            index=models.Index(fields=['permit', 'status'], name='permits_cha_permit__697ebb_idx'),
        ),
    ]
